[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
tests = 'test'
optimizer = true
optimizer_runs = 1000
solc_version = '0.8.19'
evm_version = 'paris'
ast = true
ffi = true
build_info = true
extra_output = ["abi", "bin", "metadata", "storage-layout"]
via_ir = true
remappings = [
    '@openzeppelin/contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/',
    '@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/',
    'uniswap-v3-periphery/=lib/uniswap-v3-periphery/contracts',
    'uniswap-v3-core/=lib/uniswap-v3-core/contracts'
]

[profile.production]
src = 'src'
out = 'out'
libs = ['lib']
tests = 'test'
optimizer = true
optimizer_runs = 5000
solc_version = '0.8.19'
evm_version = 'paris'
via_ir = true
extra_output = ["abi", "bin"]
remappings = [
    '@openzeppelin/contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/',
    '@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/',
    'uniswap-v3-periphery/=lib/uniswap-v3-periphery/contracts',
    'uniswap-v3-core/=lib/uniswap-v3-core/contracts'
]

[invariant]
preserve_state = true
fail_on_revert = true