[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
tests = 'test'
optimizer = true
optimizer_runs = 200
solc_version = '0.8.24'
evm_version = 'cancun'
ast = true
ffi = true
build_info = true
extra_output = ["storageLayout"]
remappings = [
    '@openzeppelin/contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/',
    '@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/',
    'uniswap-v3-periphery/=lib/uniswap-v3-periphery/contracts',
    'uniswap-v3-core/=lib/uniswap-v3-core/contracts',
    'openzeppelin-foundry-upgrades/=lib/openzeppelin-foundry-upgrades/src/'
]

[invariant]
preserve_state = true
fail_on_revert = true