[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
tests = 'test'
optimizer = true
optimizer_runs = 200
remappings = [
    'openzeppelin-contracts/=lib/openzeppelin-contracts/contracts',
    'openzeppelin-contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts',
    'uniswap-v3-periphery/=lib/uniswap-v3-periphery/contracts',
    'uniswap-v3-core/=lib/uniswap-v3-core/contracts'
]

[invariant]
preserve_state = true
fail_on_revert = true