[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
tests = 'test'
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@uniswap/=lib/uniswap-v3-periphery/"
]
rpc_url = 'https://mainnet.infura.io/v3/BgrHyNCClLz9-YurnD7iLHNXR-IKdGlE'
block_number = 19946000