/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ICampaignFactory,
  ICampaignFactoryInterface,
} from "../ICampaignFactory";

const _abi = [
  {
    type: "function",
    name: "createCampaign",
    inputs: [
      {
        name: "owner",
        type: "address",
        internalType: "address",
      },
      {
        name: "data",
        type: "bytes",
        internalType: "bytes",
      },
    ],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "contract ICampaign",
      },
    ],
    stateMutability: "nonpayable",
  },
] as const;

export class ICampaignFactory__factory {
  static readonly abi = _abi;
  static createInterface(): ICampaignFactoryInterface {
    return new Interface(_abi) as ICampaignFactoryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ICampaignFactory {
    return new Contract(address, _abi, runner) as unknown as ICampaignFactory;
  }
}
